import os

S = chr(32)*4
S2 = chr(32)*8
N = chr(10)

lines = [
'from flask import Flask, render_template, request, jsonify, send_from_directory',
'import os, json, uuid',
'from database import get_db',
'from werkzeug.utils import secure_filename',
'',
'app = Flask(__name__)',
'app.config["MAX_CONTENT_LENGTH"] = 500 * 1024 * 1024',
'',
'BASE_DIR = os.path.dirname(os.path.abspath(__file__))',
'UPLOAD_DIR = os.path.join(BASE_DIR, "uploads")',
'VIDEO_DIR = os.path.join(UPLOAD_DIR, "videos")',
'PPTX_DIR = os.path.join(UPLOAD_DIR, "pptx")',
'os.makedirs(VIDEO_DIR, exist_ok=True)',
'os.makedirs(PPTX_DIR, exist_ok=True)',
'',
'@app.route("/")',
'def index():',
S+'return render_template("index.html")',
'',
'@app.route("/uploads/videos/<path:filename>")',
'def serve_video(filename):',
S+'return send_from_directory(VIDEO_DIR, filename)',
'',
'@app.route("/api/folders", methods=["GET"])',
'def get_folders():',
S+'conn = get_db()',
S+'rows = conn.execute("SELECT * FROM folders ORDER BY name").fetchall()',
S+'conn.close()',
S+'return jsonify([dict(r) for r in rows])',
'',
'@app.route("/api/folders", methods=["POST"])',
'def create_folder():',
S+'data = request.get_json()',
S+'name = data.get("name", "").strip()',
S+'parent_id = data.get("parent_id")',
S+'if not name: return jsonify({"error": "Name required"}), 400',
S+'conn = get_db()',
S+'cur = conn.execute("INSERT INTO folders (name, parent_id) VALUES (?, ?)", (name, parent_id))',
S+'conn.commit()',
S+'fid = cur.lastrowid',
S+'conn.close()',
S+'return jsonify({"id": fid, "name": name, "parent_id": parent_id}), 201',
'',
'@app.route("/api/folders/<int:fid>", methods=["PUT"])',
'def rename_folder(fid):',
S+'name = request.get_json().get("name", "").strip()',
S+'if not name: return jsonify({"error": "Name required"}), 400',
S+'conn = get_db()',
S+'conn.execute("UPDATE folders SET name = ? WHERE id = ?", (name, fid))',
S+'conn.commit()',
S+'conn.close()',
S+'return jsonify({"id": fid, "name": name})',
'',
'@app.route("/api/folders/<int:fid>", methods=["DELETE"])',
'def delete_folder(fid):',
S+'conn = get_db()',
S+'conn.execute("DELETE FROM folders WHERE id = ?", (fid,))',
S+'conn.commit()',
S+'conn.close()',
S+'return jsonify({"ok": True})',
'',
'@app.route("/api/assets", methods=["GET"])',
'def get_assets():',
S+'folder_id = request.args.get("folder_id")',
S+'conn = get_db()',
S+'base_q = "SELECT a.id, a.base_name, a.folder_id, a.created_at, v.ace_score, v.asset_info, v.thumbnail, v.uploaded_at, v.version_number as latest_version, v.id as latest_version_id, v.video_filename FROM assets a LEFT JOIN versions v ON v.asset_id = a.id AND v.is_latest = 1 WHERE a.folder_id"',
S+'if folder_id:',
S2+'rows = conn.execute(base_q + " = ? ORDER BY a.base_name", (folder_id,)).fetchall()',
S+'else:',
S2+'rows = conn.execute(base_q + " IS NULL ORDER BY a.base_name").fetchall()',
S+'conn.close()',
S+'return jsonify([dict(r) for r in rows])',
'',
'@app.route("/api/assets/<int:aid>", methods=["DELETE"])',
'def delete_asset(aid):',
S+'conn = get_db()',
S+'versions = conn.execute("SELECT * FROM versions WHERE asset_id = ?", (aid,)).fetchall()',
S+'for v in versions:',
S2+'for p in [v["video_path"], v["pptx_path"]]:',
S2+S+'if p and os.path.exists(p): os.remove(p)',
S+'conn.execute("DELETE FROM assets WHERE id = ?", (aid,))',
S+'conn.commit()',
S+'conn.close()',
S+'return jsonify({"ok": True})',
'',
'@app.route("/api/assets/<int:aid>", methods=["PUT"])',
'def update_asset(aid):',
S+'data = request.get_json()',
S+'folder_id = data.get("folder_id")',
S+'conn = get_db()',
S+'conn.execute("UPDATE assets SET folder_id = ? WHERE id = ?", (folder_id, aid))',
S+'conn.commit()',
S+'conn.close()',
S+'return jsonify({"ok": True})',
'',
'@app.route("/api/versions/<int:aid>", methods=["GET"])',
'def get_versions(aid):',
S+'conn = get_db()',
S+'rows = conn.execute("SELECT * FROM versions WHERE asset_id = ? ORDER BY version_number DESC", (aid,)).fetchall()',
S+'conn.close()',
S+'return jsonify([dict(r) for r in rows])',
'',
'@app.route("/api/upload", methods=["POST"])',
'def upload():',
S+'folder_id = request.form.get("folder_id") or None',
S+'scores_json = request.form.get("scores")',
S+'asset_info_json = request.form.get("asset_info")',
S+'thumbnail = request.form.get("thumbnail")',
S+'ace_score = request.form.get("ace_score")',
S+'video = request.files.get("video")',
S+'pptx = request.files.get("pptx")',
S+'if not video: return jsonify({"error": "Video required"}), 400',
S+'uid = str(uuid.uuid4())[:8]',
S+'orig = secure_filename(video.filename)',
S+'base_name = os.path.splitext(orig)[0]',
S+'vid_filename = uid + "_" + orig',
S+'vid_path = os.path.join(VIDEO_DIR, vid_filename)',
S+'video.save(vid_path)',
S+'pptx_filename = pptx_path = None',
S+'if pptx:',
S2+'pptx_orig = secure_filename(pptx.filename)',
S2+'pptx_filename = uid + "_" + pptx_orig',
S2+'pptx_path = os.path.join(PPTX_DIR, pptx_filename)',
S2+'pptx.save(pptx_path)',
S+'conn = get_db()',
S+'if folder_id:',
S2+'existing = conn.execute("SELECT id FROM assets WHERE base_name = ? AND folder_id = ?", (base_name, folder_id)).fetchone()',
S+'else:',
S2+'existing = conn.execute("SELECT id FROM assets WHERE base_name = ? AND folder_id IS NULL", (base_name,)).fetchone()',
S+'if existing:',
S2+'asset_id = existing["id"]',
S2+'max_v = conn.execute("SELECT MAX(version_number) v FROM versions WHERE asset_id = ?", (asset_id,)).fetchone()["v"] or 0',
S2+'version_number = max_v + 1',
S2+'conn.execute("UPDATE versions SET is_latest = 0 WHERE asset_id = ?", (asset_id,))',
S+'else:',
S2+'cur = conn.execute("INSERT INTO assets (folder_id, base_name) VALUES (?, ?)", (folder_id, base_name))',
S2+'asset_id = cur.lastrowid',
S2+'version_number = 1',
S+'conn.execute("INSERT INTO versions (asset_id, version_number, video_filename, video_path, pptx_filename, pptx_path, ace_score, kpi_data, asset_info, thumbnail, is_latest) VALUES (?,?,?,?,?,?,?,?,?,?,1)", (asset_id, version_number, vid_filename, vid_path, pptx_filename, pptx_path, ace_score, scores_json, asset_info_json, thumbnail))',
S+'conn.commit()',
S+'conn.close()',
S+'return jsonify({"ok": True, "asset_id": asset_id, "version": version_number}), 201',
'',
'@app.route("/api/versions/<int:vid>/report", methods=["POST"])',
'def add_report(vid):',
S+'pptx = request.files.get("pptx")',
S+'scores_json = request.form.get("scores")',
S+'asset_info_json = request.form.get("asset_info")',
S+'thumbnail = request.form.get("thumbnail")',
S+'ace_score = request.form.get("ace_score")',
S+'pptx_filename = pptx_path = None',
S+'if pptx:',
S2+'uid = str(uuid.uuid4())[:8]',
S2+'pptx_orig = secure_filename(pptx.filename)',
S2+'pptx_filename = uid + "_" + pptx_orig',
S2+'pptx_path = os.path.join(PPTX_DIR, pptx_filename)',
S2+'pptx.save(pptx_path)',
S+'conn = get_db()',
S+'conn.execute("UPDATE versions SET pptx_filename=?, pptx_path=?, ace_score=?, kpi_data=?, asset_info=?, thumbnail=? WHERE id=?", (pptx_filename, pptx_path, ace_score, scores_json, asset_info_json, thumbnail, vid))',
S+'conn.commit()',
S+'conn.close()',
S+'return jsonify({"ok": True})',
'',
'@app.route("/api/projects/stats")',
'def project_stats():',
S+'conn = get_db()',
S+'projects = conn.execute("SELECT id FROM folders WHERE parent_id IS NULL").fetchall()',
S+'result = {}',
S+'sql = (',
S2+'"WITH RECURSIVE pf AS ("',
S2+'"SELECT id FROM folders WHERE id = ? "',
S2+'"UNION ALL "',
S2+'"SELECT f.id FROM folders f INNER JOIN pf ON f.parent_id = pf.id) "',
S2+'"SELECT COUNT(DISTINCT a.id) as total, "',
S2+'"SUM(CASE WHEN v.ace_score >= 67 THEN 1 ELSE 0 END) as green, "',
S2+'"SUM(CASE WHEN v.ace_score >= 34 AND v.ace_score < 67 THEN 1 ELSE 0 END) as amber, "',
S2+'"SUM(CASE WHEN v.ace_score IS NOT NULL AND v.ace_score < 34 THEN 1 ELSE 0 END) as red, "',
S2+'"SUM(CASE WHEN v.ace_score IS NULL THEN 1 ELSE 0 END) as unscored "',
S2+'"FROM assets a "',
S2+'"LEFT JOIN versions v ON v.asset_id = a.id AND v.is_latest = 1 "',
S2+'"WHERE a.folder_id IN (SELECT id FROM pf)"',
S+')',
S+'for project in projects:',
S2+'pid = project["id"]',
S2+'row = conn.execute(sql, (pid,)).fetchone()',
S2+'result[str(pid)] = dict(row) if row else {"total":0,"green":0,"amber":0,"red":0,"unscored":0}',
S+'conn.close()',
S+'return jsonify(result)',
]

open('app.py', 'w').write('\n'.join(lines))
print('app.py rebuilt successfully')